### ISSUE TITLE
The schema should be (at least partially) JSONSchema compliant

### ISSUE THREAD

**Issue by anurbol** [lucagez/slow-json-stringify#10]
Hi! https://github.com/fastify/fast-json-stringify and https://github.com/mafintosh/turbo-json-parse both use JSONSchema compatible schemas. I *love* SJS' performance but I think its schema should be standard-compliant.

**Comment by tomByrer** [comment]
Could roll your own schema translator?

**Comment by lucagez** [comment]
Hi guys 👋  Sorry for being silent for so long.
@anurbol The API of `SJS` has been changed to support real `JSON` types. As you can see from the latest README.
It does not follow [jsonschema](https://json-schema.org/) by design as it aims to support the serialization of custom types via [serializers](https://github.com/lucagez/slow-json-stringify#serializers)
